---
title: "DATIC: Dyadic Data Analysis 2018 Workshop"
date: "June 25-29, 2018"
output:
  html_document:
    highlight: zenburn
    theme: flatly
    toc: yes
    toc_float: yes
    toc_depth: 3
fontsize: 12 pt
---

 > **Instructors**: Randi Garcia and Dave Kenny  
 > **Teaching Assistants**: Julianna Alvord and Emma Ning  

***

This website contains content from the 2018 DATIC workshop on Dyadic Data Analysis. The riggs data is not available for sharing publicly.    

***

# Schedule

## Day 1:  Definitions, Nonindependence, and Data  

  + Lecture and Lab 9-12
    - [Definitions](Definitions.pdf)
    - [Introduction to R](Intro_to_R_and_the_Data.html) and [Riggs Dataset](Riggs Codebook.pdf)
        -   [Script to install packages](install-packages.html)
    - [Nonindependence](Nonindependence.pdf)
    - [Data Structures and Restructuring](Data_Structures.pdf)
  + Lunch 12:00 PM to 1:15 PM  
    - [Yelp: UConn](https://www.yelp.com/search?cflt=restaurants&find_near=university-of-connecticut-storrs-2)
  + Lecture and Lab 1:15-3:30
    - [Multilevel Modeling of Dyadic Data](MLM.html): Effects of Gender and Length of Marriage on Satisfaction
    - [Introduction to the APIM](APIM.pdf)
  + Late Afternoon Session 3:30-5:00
    - Homework (optional)
    - Restructure and Do Runs on One's Own Data
    - [Individual Meetings](https://docs.google.com/spreadsheets/d/1uVj9usSealO8WTBTkXm99x7fCNPym5o5iWvIHf6J7Y8/edit?usp=sharing)

***

## Day 2: The Actor-Partner Interdependence Model

  + Lecture and Lab 9-12
    - [Indistinguishable Dyads](Indistinguishable.html): Effects of Attachment Anxiety on Satisfaction
    - [Distinguishable Dyads](Distinguishable.html): Results Differing by Gender
    - [Power Analyses](Power.pdf)
  + Lunch 12:00 PM to 1:15 PM  
  + Lecture and Lab 1:15-3:30
    - [Test of Distinguishability](Test_for_Distinguishability.html)
    - [Testing for Patterns](Patterns.html)
    - [Actor-Partner Interactions](Actor-Partner_Interactions.html)
	  - [APIM_MM Dingy App](Dingy_Output.pdf)
  + Late Afternoon Session 3:30-5:00
    - Homework (optional)
    - Do Runs on One's Own Data
    - [Individual Meetings](https://docs.google.com/spreadsheets/d/1uVj9usSealO8WTBTkXm99x7fCNPym5o5iWvIHf6J7Y8/edit?usp=sharing)

***

## Day 3: Moderation and Mediation

  + Lecture and Lab 9-12
    - [Moderation Introduction](Moderation of the APIM.pdf)
    - [Moderation in the APIM](Moderation_in_the_APIM.html): Attachment Avoidance Moderating the Effect of Attachment Anxiety on Satisfaction
  + Lunch 12:00 PM to 1:15 PM  
  + Lecture and Lab 1:15-3:30
    - [Mediation Introduction (slides)](Mediation of the APIM.pdf)  
        -  [Figures only](Mediation_BONUS_figures.html)  
        -  [Full Handout](Mediation_handout.pdf)
    - [Mediation in the APIM](Mediation_in_the_APIM.html): Attachment Anxiety Mediating the Effect of Childhood Abuse on Satisfaction  
    - [APIMoM and APIMeM Apps](APIMeMoM.pdf)	
  + Late Afternoon Session 3:30-5:00
    - Homework (optional)
    - Do Runs on One's Own Data
    - [Individual Meetings](https://docs.google.com/spreadsheets/d/1uVj9usSealO8WTBTkXm99x7fCNPym5o5iWvIHf6J7Y8/edit?usp=sharing)

***

## Day 4: Break-out Sessions

### Over-Time Models of Dyadic Data

  + Lecture and Computer Workshop 9-12 and 1:15-3:30
    - [Introduction](Over Time_Intro.pdf)
    - [Kashy Dataset](Kashy Codebook.pdf)
    - Growth Curve Models: [Slides](Growth Curve.pdf) and [Examples](Growth_Curve_Modeling.html)  
        -   Individual Growth Curve  
        -   Dyadic Growth Curves  
  + Lunch 12:00 PM to 1:15 PM  
  + Lecture and Lab 1:15-3:30
    - [Repeated Measures Analysis](Repeated_Measures.html): Effect of Day and Gender on Satisfaction	
    - [Stability-Influence Model](Stability-Influence_Model.html): Effect of Partner's Satisfaction on Respondent's Satisfaction 
    - [APIM Person-Centered](APIM_OverTime.html)
  + Late Afternoon Session 3:30-5:00
    - Homework (optional)
    - Do Runs on One's Own Data
    - [Individual Meetings](https://docs.google.com/spreadsheets/d/1uVj9usSealO8WTBTkXm99x7fCNPym5o5iWvIHf6J7Y8/edit?usp=sharing) 

### Structural Equation Modeling for Dyadic Data

  + Lecture and Computer Workshop 9-12 and 1:15-3:30
    - [Acitelli Dataset](Acitelli Codebook.pdf)
    - Introduction to Structural Equation Modeling
    - [APIM with SEM](APIM_SEM.html)
    - Model Fit
  + Lunch 12:00 PM to 1:15 PM  
  + Lecture and Lab 1:15-3:30
    - [Mediation with SEM](Mediation_SEM.html)
    - [Confirmatory Factor Analysis with Dyads](ConfirmatoryFactorAnalysis.html)
    - [The Common Fate Model](CommonFateModel.html)
  + Late Afternoon Session 3:30-5:00
    - Homework (optional)
    - Do Runs on One's Own Data
    - [Individual Meetings](https://docs.google.com/spreadsheets/d/1uVj9usSealO8WTBTkXm99x7fCNPym5o5iWvIHf6J7Y8/edit?usp=sharing) 
    
***

## Day 5: Additional Topics

  + Lecture 9-12
    - [Presentation and Doing Dyadic Data Analysis Right](Presentation.pdf)
    - [DyadR](https://github.com/RandiLGarcia/dyadr)
    - [R: Advantages and Disadvantages](Advantages and Disadvantages of R.pdf)
    - MLM versus SEM
    - Alternative Dyadic Models and Estimation Methods  
        - [Generalized Linear Mixed Models](Generalized_Linear_Mixed_Models___GEE.html)  
        - [Generalized Estimating Equations (GEE)](Generalized_Linear_Mixed_Models___GEE.html)  
    - [Alternative Dyadic Designs](designs.pdf)  
        - One-with-Many  
        - Social Relations Model  
        - GAPIM  
  + Group Lunch 12-1:15

***

# Links to Apps and `dyadr`

  + [ItoP](https://davidakenny.shinyapps.io/ItoP/)
  + [DtoP](https://davidakenny.shinyapps.io/DtoP/)
  + [ItoD](https://davidakenny.shinyapps.io/ItoD/)
  + [APIMPower](https://robert-a-ackerman.shinyapps.io/APIMPowerRdis/)
  + [APIM_MM](https://davidakenny.shinyapps.io/APIM_MM/)
  + [Dingy](https://davidakenny.shinyapps.io/Dingy/)
  + [APIMeM](https://davidakenny.shinyapps.io/APIMeM/)
  + [APIMoM](https://davidakenny.shinyapps.io/APIMoM/)
  + [dyadr gitHub](https://github.com/RandiLGarcia/dyadr)

# Cheatsheets and R Tutorials

  + [All cheatsheets](https://www.rstudio.com/resources/cheatsheets/)
  + [dplyr cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
  + [ggplot2 cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf)
  + [RMarkdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)  
    - [Advanced RMarkdown](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html)
    
# Other Helpful Links

  + [UConn Map](http://maps.uconn.edu/index.php)
  + [Dave's Website](http://davidakenny.net/index.htm)
  + [DyadR page Webpage](http://davidakenny.net/DyadR/DyadRweb.htm)
  + [R for Data Science by Hadley Wickham and Garrett Grolemund](http://r4ds.had.co.nz/index.html)
